### ISSUE TITLE
Connection Pool only using one member

### ISSUE THREAD

**Issue by matthewjstanford** [simplereach/helenus#134] opened 2014-01-28 16:46 UTC
When connection pooling is enabled (hostPoolSize >1) the pool only uses the first member of the pool to send queries.  It should distribute the workload over the entire pool.

The 'connect' event is emitted after the first member of the pool is configured.  Well, I had 10 members configured, but only 1 was seeing traffic (as shown by the network stats).  All 10 sockets were open and established, but helenus was only using that first one.

In this gist you'll see that the original helenus code causes large TCP queues on a single socket, while the others remain idle.  When the code was modified to wait for the pool to initialize the workload is distributed over all sockets.
https://gist.github.com/matthewjstanford/8671227

**Comment by devdazed** [comment] 2014-02-17 16:41
The main issue I see with the approach in #135 is that if a node is down then it will never call back.  The intended behavior is that once a single node is up you can start querying and the nodes will pop into the good nodes list as they become available.

The issue with your gist is that you are running `pool.cql` in a tight loop.  This means that the callbacks for the other nodes finishing their connections are deferred until the end of the loop and since there is only one connection available at the time (because it was opened before the loop started) it uses this one and only this one.

try updating your test to have a [setImmediate](http://stackoverflow.com/questions/15349733/setimmediate-vs-nexttick) like this:

``` js
    for(var i = 1; i <= iterations; i += 1){
      function query(i){
        setImmediate(function(){
            vals = [i];
            pool.cql(stmt, vals, { gzip:true }, cb);
        });
      }
      query(i);
    }
```

This will put the execution at the end of the event loop giving the connections time to enter the pool.

In reality this isn't needed because the typical use-case isn't to put tight loops around queries.  I'm going to close this as this is now so much a function of the driver as it is of nodejs in general.  If I am misunderstanding the problem then I can re-open.

**Closed as completed by devdazed** 2014-02-17 16:41 UTC
