### ISSUE TITLE
Problems with timeuuid, CQL3 and INSERT

### ISSUE THREAD

**Issue by whoisvolos** [simplereach/helenus#118] opened 2013-10-08 13:24 UTC
Good day.

When I try to insert script-generated timeuuid into CF with this type I get HelenusInvalidRequestException.

``` javascript
pool.cql('INSERT INTO sometable(time_id) VALUES(?)', [ helenus.TimeUUID.fromTimestamp(new Date()) ], function(err) { ... });
```

err is { [HelenusInvalidRequestException: Unknown timeuuid representation: time_id] name: 'HelenusInvalidRequestException' }

I think this is because this cmd adds single quotes to uuid.

**Comment by whoisvolos** [comment] 2013-10-08 14:10
I've added UUID type check in escapeCQL function in connection.js. Though I have good CQL now (checked @ formatCQL func: "INSERT INTO sometable(time_id) VALUES(ccf4ad07-2469-11e3-8bdc-2fe99ee3755a)") I'm still gettin same error.

**Comment by devdazed** [comment] 2013-10-08 14:33
This is a duplicate of #98, i just merged the changes, somehow it didn't get into the master branch when I pulled.  This should fix your issue as well. i'll be dropping a point release a little later.

**Closed as completed** 2013-10-08 15:39 UTC
